amanda_sam/week_05/day_03/ocean_on_rails/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file,
  # see http://guides.rubyonrails.org/routing.html


  get '/oceans' => 'oceans#index'
  get '/oceans/new' => 'oceans#new', :as => 'ocean_new'

  post '/oceans' => 'oceans#create'

  get '/oceans/:id' => 'oceans#show', :as => 'ocean'

  post '/oceans/:id/delete' => 'oceans#destroy', :as => 'ocean_delete'

  get '/oceans/:id/edit' => 'oceans#edit', :as => 'ocean_edit'

  post '/oceans/:id' => 'oceans#update'

end

amanda_sam/week_05/day_03/ocean_on_rails/app/models/ocean.rb
# == Schema Information
#
# Table name: oceans
#
#  id         :integer          not null, primary key
#  name       :text
#  image      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#


class Ocean < ActiveRecord::Base
end

amanda_sam/week_05/day_03/ocean_on_rails/app/controllers/oceans_controller.rb
class OceansController < ApplicationController

  def index
    @oceans = Ocean.all
  end


  def new
  end


  def create
    ocean = Ocean.create :name => params[:name], :image => params[:image], :area => params[:area], :volume => params[:volume], :depth => params[:depth]
    redirect_to ocean_path(ocean.id)
  end


  def show
    @ocean = Ocean.find params[:id]
  end


  def destroy
    ocean = Ocean.find params[:id]
    ocean.destroy
    redirect_to oceans_path
  end


  def edit
    @ocean = Ocean.find params[:id]
  end


  def update
    ocean = Ocean.find params[:id]
    ocean.update :name => params[:name], :image => params[:image], :area => params[:area], :volume => params[:volume], :depth => params[:depth]
    redirect_to ocean_path(ocean.id)
  end
end

amanda_sam/week_05/day_03/ocean_on_rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OceanOnRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <!-- the class of container is linked with CSS -->
      <nav>
        <%= link_to "All oceans", oceans_path %>
        <%= link_to "New ocean", ocean_new_path %>
      </nav>

      <%= yield %>
    </div>
  </body>
</html>