reeta_shrestha/week_05/day_02/movies_app/config/routes.rb
Rails.application.routes.draw do
  get '/movies' => 'movies#index'

  get '/movies/new' => 'movies#new', :as => 'movie_new'

  post '/movies' => 'movies#create'

  get '/movies/:id' => 'movies#show', :as => 'movie'

  post '/movies/:id/delete' => 'movies#destroy', :as => 'movie_delete'

  get '/movies/:id/edit' => 'movies#edit', :as => 'movies_edit'

  post '/movies/:id' => 'movies#update'


end

reeta_shrestha/week_05/day_02/movies_app/app/models/movie.rb
class Movie < ActiveRecord::Base
end

reeta_shrestha/week_05/day_02/movies_app/app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movie.all
  end

  def new
  end

  def create
    movie = Movie.create :title => params[:title], :image => params[:image], :released_date => params[:released_date], :ratings => params[:ratings], :synopsis => params[:synopsis]

    redirect_to movies_path(movie.id)
  end

  def show
    @movie = Movie.find params[:id]
  end

  def destroy
    movie = Movie.find params[:id]
    movie.destroy
    redirect_to movies_path
  end

  def edit
    @movie = Movie.find params[:id]
  end

  def update
    movie = Movie.find params[:id]
    movie.update :title => params[:title], :image => params[:image], :released_date => params[:released_date], :ratings => params[:ratings], :synopsis => params[:synopsis]

    redirect_to movie_path(movie.id)
  end

end

reeta_shrestha/week_05/day_02/movies_app/app/views/movies/edit.html.erb
<h1>Edit Movie</h1>
<form action='<%=movie_path(@movie.id) %>' method="post">
  <label for="title">Title:</label>
  <input type="text" id="title" name="title" value="<%=@movie.title%>" placeholder="Add new Movie to the database" autofocus required>

planet_path(@planet.id
  <label for="image">Image:</label>
  <input type="url" id="image" name="image" value="<%=@movie.image%>" placeholder="https://">

  <label for="released_date">Release Date:</label>
  <input type="text" id="released_date" name="released_date" value="<%=@movie.released_date%>" placeholder="2017 August">

  <label for="ratings">Ratings:</label>
  <input type="number" id="ratings" name="ratings" value="<%=@movie.ratings%>" placeholder="Rate between 1 to 5">

  <label for="synopsis">Synopsis:</label>
  <input type="text" id="synopsis" name="synopsis" value="<%=@movie.synopsis%>" placeholder="Once there was a language called Ruby...">

  <button>Add Movie to the Database</button>

</form>

reeta_shrestha/week_05/day_02/movies_app/app/views/movies/index.html.erb
<h1>Movies Index</h1>

<ul>
<% @movies.each do |movie| %>
  <li>
    <%= link_to(movie.title, movie_path(movie.id)) %>
    <%= link_to(movie.image, movie_path(movie.id)) %>
    <p><%= truncate(movie.synopsis, :length =>50)%></p>
  </li>
<% end %>
</ul>

reeta_shrestha/week_05/day_02/movies_app/app/views/movies/new.html.erb
<h1>New Movie</h1>
<form action='<%= movies_path %>' method="post">
  <label for="title">Title:</label>
  <input type="text" id="title" name="title" placeholder="Add new Movie to the database" autofocus required>

  <label for="image">Image:</label>
  <input type="url" id="image" name="image" placeholder="https://">

  <label for="released_date">Release Date:</label>
  <input type="text" id="released_date" name="released_date" placeholder="2017 August">

  <label for="ratings">Ratings:</label>
  <input type="number" id="ratings" name="ratings" placeholder="Rate between 1 to 5">

  <label for="synopsis">Synopsis:</label>
  <input type="text" id="synopsis" name="synopsis" placeholder="Once there was a language called Ruby...">

  <button>Add Movie to the Database</button>

</form>

reeta_shrestha/week_05/day_02/movies_app/app/views/movies/show.html.erb
<h1>Show Movie Details</h1>
<ul>
  <li>
    <p>Title: <%= @movie.title %></p>
    <%= @movie.image %>
    <p>Released on: <%= @movie.released_date %></p>
    <p>Ratings: <%= @movie.ratings %></p>
    <p>Synopsis: <%= @movie.synopsis %></p>
  </li>
</ul>

<div class="controls">
  <%= button_to 'Delete Movie', movie_delete_path(@movie.id) %>
<%= link_to 'Edit Movie', movies_edit_path(@movie.id) %>

</div>