mitchell_backhouse/week_05/day_03/association_app/config/routes.rb
Rails.application.routes.draw do
  root to: 'manufacturers#index'

  resources :manufacturers
  resources :cars
end

mitchell_backhouse/week_05/day_03/association_app/app/models/car.rb
class Car < ApplicationRecord
  extend FriendlyId
  friendly_id :model, use: :slugged

  belongs_to :manufacturer
end

mitchell_backhouse/week_05/day_03/association_app/app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :cars
end

mitchell_backhouse/week_05/day_03/association_app/app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def new
    @car = Car.new
  end

  def create
    car = Car.create car_params

    redirect_to car
  end

  def edit
    @car = Car.friendly.find params[:id]
  end

  def update
    car = Car.friendly.find params[:id]
    car.update car_params

    redirect_to car
  end

  def show
    @car = Car.friendly.find params[:id]
  end

  def delete
    car = Car.friendly.find params[:id]
    car.destroy

    redirect_to cars_path
  end

  private

  def car_params
    params.require(:car).permit(:make, :model, :hp, :tq, :category, :image, :manufacturer_id)
  end
end

mitchell_backhouse/week_05/day_03/association_app/app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  def index
    @manufacturers = Manufacturer.all
  end

  def new
    @manufacturer = Manufacturer.new
  end

  def create
    manufacturer = Manufacturer.create manufacturer_params

    redirect_to manufacturer
  end

  def edit
    @manufacturer = Manufacturer.friendly.find params[:id]
  end

  def update
    manufacturer = Manufacturer.friendly.find params[:id]
    manufacturer.update manufacturer_params

    redirect_to manufacturer
  end

  def show
    @manufacturer = Manufacturer.friendly.find params[:id]
  end

  def delete
    manufacturer = Manufacturer.friendly.find params[:id]
    manufacturer.destroy

    redirect_to manufacturers_path
  end

  private

  def manufacturer_params
    params.require(:manufacturer).permit(:name, :founded, :description, :image)
  end
end

mitchell_backhouse/week_05/day_03/association_app/app/helpers/cars_helper.rb
module CarsHelper
end

mitchell_backhouse/week_05/day_03/association_app/app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

mitchell_backhouse/week_05/day_03/association_app/app/views/layouts/_breadcrumb.html.erb
<% if params[:controller] == "manufacturers" %>
  <div class="breadcrumb">
    <div class="container">
      <%= link_to 'New Manufacturer', new_manufacturer_path, class: 'manBread' %>
    </div>
  </div>
  <% if params[:controller] == "manufacturers" && params[:action] == "show" %>
    <div class="container">
      <div class="manEdit">
        <%= link_to 'Edit', edit_manufacturer_path(@manufacturer) %>
      </div>
    </div>
  <% end %>
<% elsif params[:controller] == "cars" %>
  <div class="breadcrumb">
    <div class="container">
      <%= link_to 'New Car', new_car_path, class: 'carBread' %>
    </div>
  </div>
  <% if params[:controller] == "cars" && params[:action] == "show" %>
    <div class="container">
      <div class="carEdit">
        <%= link_to 'Edit', edit_car_path(@car) %>
      </div>
    </div>
  <% end %>
<% end %>

mitchell_backhouse/week_05/day_03/association_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manufacturers and Cars</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="container">
        <nav>
          <%= active_link_to 'Manufacturers', manufacturers_path, class_active: 'selected' %>
          <%= active_link_to 'Cars', cars_path, class_active: 'selected' %>
        </nav>
      </div>
    </header>
    <%= render partial: 'layouts/breadcrumb' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>