joshua_mcevoy/week_05/day_02/solar_system/config/routes.rb
Rails.application.routes.draw do
  get '/planets' => 'planets#index'
  get '/planets/new' => 'planets#new', :as => 'planet_new'
  post '/planets' => 'planets#create'
  get '/planets/:id' => 'planets#show', :as => 'planet'
  post '/planets/:id/delete' => 'planets#destroy', :as => 'planet_delete'
  get '/planets/:id/edit' => 'planets#edit', :as => 'planet_edit'
  post '/planets/:id' => 'planets#update'
end

joshua_mcevoy/week_05/day_02/solar_system/app/models/planet.rb
# == Schema Information
#
# Table name: planets
#
#  id         :integer          not null, primary key
#  name       :text
#  image      :text
#  orbit      :float
#  diameter   :float
#  mass       :float
#  moons      :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Planet < ActiveRecord::Base
end

joshua_mcevoy/week_05/day_02/solar_system/app/controllers/planets_controller.rb
class PlanetsController < ApplicationController

  def index
    @planets = Planet.all
  end

  def new
  end

  def create
    planet = Planet.create :name => params[:name], :image => params[:image], :orbit => params[:orbit], :diameter => params[:diameter], :mass => params[:mass], :moons => params[:moons]
    redirect_to planet_path(planet.id)
  end

  def show
    @planet = Planet.find params[:id]
  end

  def destroy
    planet = Planet.find params[:id]
    planet.destroy
    redirect_to planets_path
  end

  def edit
    @planet = Planet.find params[:id]
  end

  def update
    planet = Planet.find params[:id]
    planet.update :name => params[:name], :image => params[:image], :orbit => params[:orbit], :diameter => params[:diameter], :mass => params[:mass], :moons => params[:moons]
    redirect_to planet_path(planet.id)
  end
end

joshua_mcevoy/week_05/day_02/solar_system/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SolarSystem</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

      <nav>
        <%= link_to "All planets", planets_path %>
        <%= link_to "New planet", planet_new_path %>
      </nav>

      <%= yield %>
    </div>
  </body>
</html>